### ISSUE TITLE
The editor does not work when changing languages

### ISSUE THREAD

**Issue by donlinux** [opensource-socialnetwork/HelloWorld#1]
I can edit the in page Bio,  Terms, Policy in English but when I switch to Spanish the editor does not appear and it cannot be edited there is no text area.

Ossn version free 5.2
cpsrvd 11.78.0.38
MySQL, MariaDB, or equivalent 5.6.41-84.1-log
Versión del cliente de base de datos: libmysql - 5.1.73
extensión PHP: mysqliDocumentación curlDocumentación mbstringDocumentación
Versión de PHP: 7.2.7
Apache/2.4.39 (cPanel) OpenSSL/1.0.2u mod_bwlimited/1.4 Phusion_Passenger/6.0.4
Cache disabled
URL site: http://todosida.org/chatpositivos/

Regards

![spanish-bio](https://user-images.githubusercontent.com/6231881/82429274-ea48e980-9a8b-11ea-84a2-12c4a47c4abf.png)
![english](https://user-images.githubusercontent.com/6231881/82429281-eb7a1680-9a8b-11ea-9254-0533814528b9.png)
![spanish](https://user-images.githubusercontent.com/6231881/82429290-eddc7080-9a8b-11ea-968b-676be544b80f.png)
![english-terms](https://user-images.githubusercontent.com/6231881/82429933-ed90a500-9a8c-11ea-85d8-d32f0428a7e7.png)

**Comment by lianglee** [comment]
Thanks for providing details,  can you provide the screenshot of browser console also? 
I can not able to register to your website either

**Comment by donlinux** [comment]
Thanks for answering. I can create users from outside, attached screenshot of a new user created by me.

![captura-ossn](https://user-images.githubusercontent.com/6231881/82486716-949d2d00-9add-11ea-9f57-d364665c3851.png)

![captura-ossn1](https://user-images.githubusercontent.com/6231881/82486721-95ce5a00-9add-11ea-9f3b-61c69ae5a4e7.png)

![captura-ossn2](https://user-images.githubusercontent.com/6231881/82486994-01182c00-9ade-11ea-87ca-c477a21e4ec9.png)

**Comment by donlinux** [comment]
Thanks for answering. I can create users from outside, attached screenshot of a new user created by me.

![captura-ossn](https://user-images.githubusercontent.com/6231881/82486716-949d2d00-9add-11ea-9f57-d364665c3851.png)

![captura-ossn1](https://user-images.githubusercontent.com/6231881/82486721-95ce5a00-9add-11ea-9f3b-61c69ae5a4e7.png)

![captura-ossn2](https://user-images.githubusercontent.com/6231881/82486994-01182c00-9ade-11ea-87ca-c477a21e4ec9.png)

**Comment by donlinux** [comment]
Issue resolved, missing the es.js file for the Spanish translation of the Tinymce Editor, when creating it works perfectly.

**Comment by lianglee** [comment]
Oh yes,  thanks for finding out the problem. Much appreciated for letting us the cause :)
